### ISSUE TITLE
Issue with custom mesh.

### ISSUE THREAD

**Issue by lcaraffa** [ln-12/blainder-range-scanner#18]
Hi!
I would like to know if it's possible to make a scan from every kind of scene?
I'm trying to use the "lego scene" blender file from the original "nerf" dataset (file available here : https://drive.google.com/file/d/1yDB7Pmo2KSPw2d0J7E6FHvb-sU0DdTvX/view?usp=sharing), but it's not working
I'm interested about the X,Y,Z and the intensity of every scan, can you help me?

My setup : the standalone blender 2.93 with the add-on (working well with the example scene).
I first did "make single user" on the mesh (I had an issue with it)
Then i had this error : 
"closestHit.color = materialProperty.color
AttributeError: 'NoneType' object has no attribute 'color'"
Do you know if there is any hack in order to make the scan possible? (

Thank you very much for your help.
ps : Thanks for sharing your code, 
it would be very helpful for me if I can make this scan.

**Comment by ln-12** [comment]
Hey @lcaraffa, thanks for your interest. The problem is that you use some non supported materials. As described [here](https://github.com/ln-12/blainder-range-scanner#diffuse-material), you can currently only use `Princinpled BSDF` and `Glass BSDF` as material. Looking at the console logging, I get many errors like this:
```
Unknown material type for object Plane.001!
EMISSION
Unknown material type for object Plane.001!
MIX_SHADER
```
`Emission`, `BSDF_DIFFUSE` and `Mix Shader` from your scene are unfortunately not implemented yet. So you would need to swap your materials with some `Princinpled BSDF` based ones.
